In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
#读取IDS2018数据集
#存储数据集的目录
filePath = '../../data/CSE-CIC-IDS2018/'
files=os.listdir(filePath)

In [3]:
files

['02-14-2018.csv',
 '02-15-2018.csv',
 '02-16-2018.csv',
 '02-20-2018.csv',
 '02-21-2018.csv',
 '02-22-2018.csv',
 '02-23-2018.csv',
 '02-28-2018.csv',
 '03-01-2018.csv',
 '03-02-2018.csv']

In [4]:
for i in range(0,9):
    df=pd.read_csv(filePath+files[i],low_memory=False)

    # 两列重复， Fwd Header Length和 Fwd Header Length.1
    # df = df.drop('Flow ID',axis=1) # 删除重复列
    # df = df.drop('Src IP',axis=1) # 删除重复列
    # df = df.drop('Src Port',axis=1) # 删除重复列
    # df = df.drop('Dst IP',axis=1) # 删除重复列
    df = df.drop('Protocol',axis=1) # 删除重复列
    df = df.drop('Timestamp',axis=1) # 删除重复列
    # df = df.drop('',axis=1) # 删除重复列

    df[df["Dst Port"]=="Dst Port"].index

    # df.drop(df[df.oh>3].index)
    df=df.drop(df[df["Dst Port"]=="Dst Port"].index)
    df=df[~df.isin([np.nan, np.inf, -np.inf]).any(axis=1)]
    df.to_csv(files[i],index=None)
    # df.dropna(axis=0, how='any', inplace=True)

    # df.info()

In [5]:
# 合并数据集
df=pd.DataFrame()
for file in files:
    tmp_df=pd.read_csv(filePath+file)
    df = pd.concat([df,tmp_df],axis=0).reset_index(drop=True)

C:\Users\87211\AppData\Local\Temp\ipykernel_29740\1587589438.py:4: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  tmp_df=pd.read_csv(filePath+file)
C:\Users\87211\AppData\Local\Temp\ipykernel_29740\1587589438.py:4: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  tmp_df=pd.read_csv(filePath+file)
C:\Users\87211\AppData\Local\Temp\ipykernel_29740\1587589438.py:4: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  tmp_df=pd.read_csv(filePath+file)

In [6]:
df

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,56320859.5,139.300036,56320958,56320761,Benign,NaN,NaN,NaN,NaN
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,56320733.0,114.551299,56320814,56320652,Benign,NaN,NaN,NaN,NaN
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,56319311.5,301.934596,56319525,56319098,Benign,NaN,NaN,NaN,NaN
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,0,0.0,0.0,0,0,Benign,NaN,NaN,NaN,NaN
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,0,0.0,0.0,0,0,Benign,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16232997,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
16232998,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
16232999,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
16233000,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
16233001,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN

In [7]:
# 处理Label
Label = df['Label']
list(pd.value_counts(Label).keys())
# 使用sklearn之LabelEncoder将Label标准化
from sklearn import preprocessing
le_mul = preprocessing.LabelEncoder()
le_bin = preprocessing.LabelBinarizer()
le_mul.fit(Label)

# 进行转化
df['Label']=le_mul.transform(Label)
# # 显示标签转换后的结果
# list(pd.value_counts(IDS2018_label_15).keys())

# # 显示数字所对应的标签
# print(le_mul.inverse_transform([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]))

In [9]:
from sklearn.model_selection import train_test_split

# 将数据集按照 7:3 的比例拆分成训练集和测试集
train_df, test_df = train_test_split(df, test_size=0.3, random_state=42)

# 将训练集和测试集保存为 CSV 文件
train_df.to_csv('../../data/CICDS2018/numeric/train_data.csv', index=False)
test_df.to_csv('../../data/CICDS2018/numeric/test_data.csv', index=False)

In [8]:
df1 = pd.read_csv('../../data/CICDS2018/numeric/train_data.csv',low_memory=False)
df2 = pd.read_csv('../../data/CICDS2018/numeric/test_data.csv',low_memory=False)

In [10]:
df1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,53,17,02/03/2018 02:28:59,3803,1,1,32,128.0,32,32,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN
1,3389,6,20/02/2018 09:04:49,5939399,11,13,1901.0,1606.0,581.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.67.78-211.157.158.66-3389-57887-6,211.157.158.66,57887.0,172.31.67.78
2,80,6,20/02/2018 04:37:49,338,2,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.66.74-72.167.239.239-55465-80-6,172.31.66.74,55465.0,72.167.239.239
3,52530,6,21/02/2018 02:25:46,14145,5,2,935,365,935,0,...,0,0.0,0.0,0,0,0,NaN,NaN,NaN,NaN
4,57709,6,21/02/2018 02:27:08,1349,5,2,935,339,935,0,...,0,0.0,0.0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11363096,53,17,20/02/2018 11:57:29,12030,1,1,40.0,168.0,40.0,40.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.0.2-172.31.66.107-53-60962-17,172.31.66.107,60962.0,172.31.0.2
11363097,80,6,02/03/2018 11:35:54,818,3,4,161,488.0,161,0,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN
11363098,53,17,20/02/2018 09:34:24,1218,1,1,38.0,90.0,38.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.0.2-172.31.65.85-53-54585-17,172.31.65.85,54585.0,172.31.0.2
11363099,53,17,02/03/2018 09:36:55,405,1,1,37,131.0,37,37,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN
11363100,443,6,28/02/2018 10:01:22,230,3,0,31,0,31,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

In [11]:
df2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,53,17,20/02/2018 02:11:48,285,1,1,36.0,52.0,36.0,36.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.0.2-172.31.68.9-53-56114-17,172.31.68.9,56114.0,172.31.0.2
1,22,6,14/02/2018 02:21:30,376499,24,20,1928,2665,640,0,...,0,0.0,0.0,0,0,15,NaN,NaN,NaN,NaN
2,53,17,20/02/2018 11:40:02,2432,1,1,39.0,211.0,39.0,39.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.0.2-172.31.66.112-53-49805-17,172.31.66.112,49805.0,172.31.0.2
3,80,6,20/02/2018 03:39:47,246562,3,4,161.0,488.0,161.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,169.254.169.254-172.31.64.60-80-52912-6,172.31.64.60,52912.0,169.254.169.254
4,53,17,20/02/2018 10:51:41,46415,2,2,66.0,450.0,33.0,33.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.0.2-172.31.67.33-53-62113-17,172.31.67.33,62113.0,172.31.0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869896,80,6,28/02/2018 05:12:57,116141538,16,14,445,706,434,0,...,94810,10000000.0,18440.76982,10000000,9952998,0,NaN,NaN,NaN,NaN
4869897,52685,6,20/02/2018 04:16:43,50,2,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,172.31.67.27-186.24.48.226-445-52685-6,172.31.67.27,445.0,186.24.48.226
4869898,51670,6,15/02/2018 01:43:08,1,3,0,53,0,53,0,...,0,0.0,0.0,0,0,0,NaN,NaN,NaN,NaN
4869899,53,17,02/03/2018 11:42:26,2619,1,1,42,139.0,42,42,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN
4869900,80,6,14/02/2018 08:46:02,53576825,2,0,0,0,0,0,...,0,0.0,0.0,0,0,0,NaN,NaN,NaN,NaN

In [13]:
# 处理Label
Label = df1['Label']
print(Label)

0           0
1           0
2           0
3           0
4           0
           ..
11363096    0
11363097    0
11363098    0
11363099    0
11363100    0
Name: Label, Length: 11363101, dtype: int64

In [14]:
list(pd.value_counts(Label).keys())

[0, 4, 6, 8, 1, 11, 15, 12, 9, 7, 10, 5, 2, 3, 14, 13]

In [17]:
# 保存前需要Reshape
label_bin = Label.values.reshape(Label.shape[0],1)
label_bin.shape

(11363101, 1)

In [18]:
# 保存标签
np.save('../../data/CICDS2018/sub/ids2018_Y.npy',label_bin)

In [27]:
pd.value_counts(Label).keys()[0]

0

In [2]:
import pandas as pd
df = pd.read_csv('../../data/CICDS2018/sub/CICIDS2018_small.csv', low_memory=False)

In [3]:
df.columns

Index(['Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [10]:
# 判断是否存在空值
df.isna().any()[df.isna().any()]

Flow Byts/s    True
dtype: bool

In [11]:
# 空值填充为0
df.fillna(value=0,inplace=True)

In [12]:
# 判断是否存在空值
df.isna().any()[df.isna().any()]

Series([], dtype: bool)

In [13]:
# 判断是否存在inf值
for column in list(df.columns)[:-1]:
    if np.isinf(df[column]).any():
        print (column)

Flow Byts/s
Flow Pkts/s

In [15]:
# 取最大值 需要排除inf 所以是索引是1
max_value = sorted(set(df['Flow Pkts/s'].values.tolist()),reverse=True)[1]
df['Flow Pkts/s'][np.isinf(df['Flow Pkts/s'])] = max_value

C:\Users\87211\AppData\Local\Temp\ipykernel_19604\1272996945.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Flow Pkts/s'][np.isinf(df['Flow Pkts/s'])] = max_value

In [16]:
# 取最大值 需要排除inf 所以是索引是1
max_value = sorted(set(df['Flow Byts/s'].values.tolist()),reverse=True)[1]
df['Flow Byts/s'][np.isinf(df['Flow Byts/s'])] = max_value

C:\Users\87211\AppData\Local\Temp\ipykernel_19604\2331130093.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Flow Byts/s'][np.isinf(df['Flow Byts/s'])] = max_value

In [17]:
# 判断是否存在inf值
for column in list(df.columns)[:-1]:
    if np.isinf(df[column]).any():
        print (column)

In [18]:
df.shape

(1623295, 79)

In [20]:
# 处理Label
Label = df['Label']

In [21]:
list(pd.value_counts(Label).keys())

['Benign',
 'DDOS attack-HOIC',
 'DDoS attacks-LOIC-HTTP',
 'DoS attacks-Hulk',
 'Bot',
 'FTP-BruteForce',
 'SSH-Bruteforce',
 'Infilteration',
 'DoS attacks-SlowHTTPTest',
 'DoS attacks-GoldenEye',
 'DoS attacks-Slowloris',
 'DDOS attack-LOIC-UDP',
 'Brute Force -Web',
 'SQL Injection',
 'Brute Force -XSS']

In [23]:
# 使用sklearn之LabelEncoder将Label标准化
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Label)

LabelEncoder()

In [24]:
# 进行转化
label_bin=le.transform(Label)
# 显示标签转换后的结果
list(pd.value_counts(label_bin).keys())

[0, 4, 6, 8, 1, 11, 14, 12, 9, 7, 10, 5, 2, 13, 3]

In [25]:
# 显示数字所对应的标签
print(le.inverse_transform([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]))

['Benign' 'Bot' 'Brute Force -Web' 'Brute Force -XSS' 'DDOS attack-HOIC'
 'DDOS attack-LOIC-UDP' 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye'
 'DoS attacks-Hulk' 'DoS attacks-SlowHTTPTest' 'DoS attacks-Slowloris'
 'FTP-BruteForce' 'Infilteration' 'SQL Injection' 'SSH-Bruteforce']

In [26]:
# 保存前需要Reshape
label_bin = label_bin.reshape(label_bin.shape[0],1)
label_bin.shape

(1623295, 1)

In [27]:
# 保存标签
np.save('../../data/CICDS2018/sub/ids2018_Y.npy',label_bin)

In [29]:
df["Label"].value_counts()

Label
Benign                      1348296
DDOS attack-HOIC              68455
DDoS attacks-LOIC-HTTP        57808
DoS attacks-Hulk              46224
Bot                           28518
FTP-BruteForce                19360
SSH-Bruteforce                18766
Infilteration                 16185
DoS attacks-SlowHTTPTest      14150
DoS attacks-GoldenEye          4164
DoS attacks-Slowloris          1110
DDOS attack-LOIC-UDP            167
Brute Force -Web                 61
SQL Injection                    16
Brute Force -XSS                 15
Name: count, dtype: int64

In [31]:
list(pd.value_counts(Label).keys())[0]
df['Label'][df['Label']==list(pd.value_counts(Label).keys())[0]].count()

1348296

In [32]:
subdf = pd.DataFrame()
for label in list(pd.value_counts(Label).keys()):
    df_temp = df[df['Label'] == label]
    if(df['Label'][df['Label']==label].count()>10293):
        df_temp = df_temp.sample(frac=0.01)
    elif(df['Label'][df['Label']==label].count()<1507):
        df_temp = df_temp.sample(frac=1)
    else:
        df_temp = df_temp.sample(frac=0.1)
    df_temp.reset_index(drop=True, inplace=True)
    # df_temp[" Label"].value_counts()
    subdf = pd.concat([df_temp,subdf])
    subdf.reset_index(drop=True, inplace=True)
subdf["Label"].value_counts()

Label
Benign                      13483
DoS attacks-Slowloris        1110
DDOS attack-HOIC              685
DDoS attacks-LOIC-HTTP        578
DoS attacks-Hulk              462
DoS attacks-GoldenEye         416
Bot                           285
FTP-BruteForce                194
SSH-Bruteforce                188
DDOS attack-LOIC-UDP          167
Infilteration                 162
DoS attacks-SlowHTTPTest      142
Brute Force -Web               61
SQL Injection                  16
Brute Force -XSS               15
Name: count, dtype: int64

In [34]:
subdf.shape

(17964, 79)

In [35]:
subdf

,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,6,674,2,0,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Brute Force -XSS
1,80,6,57157398,203,104,56330.0,190002.0,680.0,0.0,277.487685,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Brute Force -XSS
2,80,6,38,2,0,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Brute Force -XSS
3,80,6,951,2,0,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Brute Force -XSS
4,80,6,134,2,0,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Brute Force -XSS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17959,80,6,74,2,0,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
17960,52469,6,74587,2,1,38.0,0.0,38.0,0.0,19.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
17961,50644,6,999959,2,0,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
17962,53386,6,12,1,1,0.0,0.0,0.0,0.0,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
17963,3389,6,1896165,8,7,1128.0,1581.0,661.0,0.0,141.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [36]:
# 归一化处理 可选
from sklearn.preprocessing import  StandardScaler

standard_scaler_df=StandardScaler().fit_transform(subdf.iloc[:,:-1])
np.save('../../data/CICDS2018/sub/sub_X.npy',standard_scaler_df)

In [37]:
Label = subdf['Label']
# 使用sklearn之LabelEncoder将Label标准化
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Label)

LabelEncoder()

In [38]:
# 进行转化
label_le=le.transform(Label)
# 显示数字所对应的标签
print(le.inverse_transform(list(range(len(list(pd.value_counts(label_le).keys()))))))

['Benign' 'Bot' 'Brute Force -Web' 'Brute Force -XSS' 'DDOS attack-HOIC'
 'DDOS attack-LOIC-UDP' 'DDoS attacks-LOIC-HTTP' 'DoS attacks-GoldenEye'
 'DoS attacks-Hulk' 'DoS attacks-SlowHTTPTest' 'DoS attacks-Slowloris'
 'FTP-BruteForce' 'Infilteration' 'SQL Injection' 'SSH-Bruteforce']

In [39]:
label_le = label_le.reshape(label_le.shape[0],1)
label_le.shape

(17964, 1)

In [40]:
np.save('../../data/CICDS2018/sub/sub_Y.npy',label_le)