In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# 读取数据

In [3]:
a1 = pd.read_csv('../../data/UNSW-NB15/UNSW-NB15_1.csv',names=range(49),low_memory=False)
a2 = pd.read_csv('../../data/UNSW-NB15/UNSW-NB15_2.csv',names=range(49),low_memory=False)
a3 = pd.read_csv('../../data/UNSW-NB15/UNSW-NB15_3.csv',names=range(49),low_memory=False)
a4 = pd.read_csv('../../data/UNSW-NB15/UNSW-NB15_4.csv',names=range(49),low_memory=False)

In [4]:
a = pd.concat([a1,a2,a3,a4],axis=0)

In [5]:
pd.value_counts(a.iloc[:,-2])

47
Generic             215481
Exploits             44525
 Fuzzers             19195
DoS                  16353
 Reconnaissance      12228
 Fuzzers              5051
Analysis              2677
Backdoor              1795
Reconnaissance        1759
 Shellcode            1288
Backdoors              534
Shellcode              223
Worms                  174
Name: count, dtype: int64

In [6]:
a.shape

(2540047, 49)

In [7]:
a

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440039,59.166.0.5,33094,149.171.126.7,43433,tcp,FIN,0.087306,320,1828,31,...,,1,2,3,3,1,1,3,NaN,0
440040,59.166.0.7,20848,149.171.126.4,21,tcp,CON,0.365058,456,346,31,...,2,2,2,2,2,2,2,2,NaN,0
440041,59.166.0.3,21511,149.171.126.9,21,tcp,CON,6.335154,1802,2088,31,...,2,2,2,4,2,2,2,2,NaN,0
440042,59.166.0.9,35433,149.171.126.0,80,tcp,CON,2.200934,3498,166054,31,...,,1,1,2,4,2,2,2,NaN,0
440043,175.45.176.0,17293,149.171.126.17,110,tcp,CON,0.942984,574,676,62,...,,1,1,2,4,2,2,2,Exploits,1

In [8]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2540047 entries, 0 to 440043
Data columns (total 49 columns):
 #   Column  Dtype
---  ------  -----
 0   0       object
 1   1       object
 2   2       object
 3   3       object
 4   4       object
 5   5       object
 6   6       float64
 7   7       int64
 8   8       int64
 9   9       int64
 10  10      int64
 11  11      int64
 12  12      int64
 13  13      object
 14  14      float64
 15  15      float64
 16  16      int64
 17  17      int64
 18  18      int64
 19  19      int64
 20  20      int64
 21  21      int64
 22  22      int64
 23  23      int64
 24  24      int64
 25  25      int64
 26  26      float64
 27  27      float64
 28  28      int64
 29  29      int64
 30  30      float64
 31  31      float64
 32  32      float64
 33  33      float64
 34  34      float64
 35  35      int64
 36  36      int64
 37  37      float64
 38  38      float64
 39  39      object
 40  40      int64
 41  41      int64
 42  42      int64
 43  43      int64
 44  44      int64
 45  45      int64
 46  46      int64
 47  47      object
 48  48      int64
dtypes: float64(12), int64(28), object(9)
memory usage: 969.0+ MB

## 类别特征数值化

### 序号4列数据数值化

In [9]:
pro = a[4]

In [10]:
print(pro)

0         udp
1         udp
2         udp
3         udp
4         udp
         ...
440039    tcp
440040    tcp
440041    tcp
440042    tcp
440043    tcp
Name: 4, Length: 2540047, dtype: object

In [12]:
lab = pro.unique()

In [13]:
print(lab)
lab.shape

['udp' 'arp' 'tcp' 'ospf' 'icmp' 'igmp' 'sctp' 'udt' 'sep' 'sun-nd'
 'swipe' 'mobile' 'pim' 'rtp' 'ipnip' 'ip' 'ggp' 'st2' 'egp' 'cbt' 'emcon'
 'nvp' 'igp' 'xnet' 'argus' 'bbn-rcc' 'chaos' 'pup' 'hmp' 'mux' 'dcn'
 'prm' 'trunk-1' 'xns-idp' 'trunk-2' 'leaf-1' 'leaf-2' 'irtp' 'rdp'
 'iso-tp4' 'netblt' 'mfe-nsp' 'merit-inp' '3pc' 'xtp' 'idpr' 'tp++' 'ddp'
 'idpr-cmtp' 'ipv6' 'il' 'idrp' 'ipv6-frag' 'sdrp' 'ipv6-route' 'gre'
 'rsvp' 'mhrp' 'bna' 'esp' 'i-nlsp' 'narp' 'ipv6-no' 'tlsp' 'skip'
 'ipv6-opts' 'any' 'cftp' 'sat-expak' 'kryptolan' 'rvd' 'ippc' 'sat-mon'
 'ipcv' 'visa' 'cpnx' 'cphb' 'wsn' 'pvp' 'br-sat-mon' 'wb-mon' 'wb-expak'
 'iso-ip' 'secure-vmtp' 'vmtp' 'vines' 'ttp' 'nsfnet-igp' 'dgp' 'tcf'
 'eigrp' 'sprite-rpc' 'larp' 'mtp' 'ax.25' 'ipip' 'micp' 'aes-sp3-d'
 'encap' 'etherip' 'pri-enc' 'gmtp' 'pnni' 'ifmp' 'aris' 'qnx' 'a/n'
 'scps' 'snp' 'ipcomp' 'compaq-peer' 'ipx-n-ip' 'vrrp' 'zero' 'pgm' 'iatp'
 'ddx' 'l2tp' 'srp' 'stp' 'smp' 'uti' 'sm' 'ptp' 'fire' 'crtp' 'isis'
 'crudp' 'sccopmce' 'sps' 'pipe' 'iplt' 'unas' 'fc' 'ib']

(135,)

In [14]:
# 数值化

from sklearn import preprocessing
target = lab

for x in target:
    label = preprocessing.LabelEncoder()
    a[4] = label.fit_transform(a[4])

### 序号5数值化

In [15]:
lab2 = a[5].unique()

In [17]:
print(lab2)
lab2.shape

['CON' 'INT' 'FIN' 'URH' 'REQ' 'ECO' 'RST' 'CLO' 'TXD' 'URN' 'no' 'ACC'
 'PAR' 'MAS' 'TST' 'ECR']

(16,)

In [18]:
# 数值化

from sklearn import preprocessing
target = lab2

for x in target:
    label = preprocessing.LabelEncoder()
    a[5] = label.fit_transform(a[5])

### 序号13数值化

In [19]:
lab3 = a[13].unique()

In [20]:
print(lab3)
lab3.shape

['dns' '-' 'http' 'smtp' 'ftp-data' 'ftp' 'ssh' 'pop3' 'snmp' 'ssl' 'irc'
 'radius' 'dhcp']

(13,)

In [21]:
# 数值化

from sklearn import preprocessing
target = lab3

for x in target:
    label = preprocessing.LabelEncoder()
    a[13] = label.fit_transform(a[13])

In [22]:
a

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,120,2,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,120,2,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,120,2,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,120,2,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,120,2,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440039,59.166.0.5,33094,149.171.126.7,43433,114,5,0.087306,320,1828,31,...,,1,2,3,3,1,1,3,NaN,0
440040,59.166.0.7,20848,149.171.126.4,21,114,2,0.365058,456,346,31,...,2,2,2,2,2,2,2,2,NaN,0
440041,59.166.0.3,21511,149.171.126.9,21,114,2,6.335154,1802,2088,31,...,2,2,2,4,2,2,2,2,NaN,0
440042,59.166.0.9,35433,149.171.126.0,80,114,2,2.200934,3498,166054,31,...,,1,1,2,4,2,2,2,NaN,0
440043,175.45.176.0,17293,149.171.126.17,110,114,2,0.942984,574,676,62,...,,1,1,2,4,2,2,2,Exploits,1

In [23]:
A = a[range(47)] #取数据部分

In [24]:
A

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,59.166.0.0,1390,149.171.126.6,53,120,2,0.001055,132,164,31,...,0.0,0.0,0,3,7,1,3,1,1,1
1,59.166.0.0,33661,149.171.126.9,1024,120,2,0.036133,528,304,31,...,0.0,0.0,0,2,4,2,3,1,1,2
2,59.166.0.6,1464,149.171.126.7,53,120,2,0.001119,146,178,31,...,0.0,0.0,0,12,8,1,2,2,1,1
3,59.166.0.5,3593,149.171.126.5,53,120,2,0.001209,132,164,31,...,0.0,0.0,0,6,9,1,1,1,1,1
4,59.166.0.3,49664,149.171.126.0,53,120,2,0.001169,146,178,31,...,0.0,0.0,0,7,9,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440039,59.166.0.5,33094,149.171.126.7,43433,114,5,0.087306,320,1828,31,...,NaN,NaN,,1,2,3,3,1,1,3
440040,59.166.0.7,20848,149.171.126.4,21,114,2,0.365058,456,346,31,...,NaN,2.0,2,2,2,2,2,2,2,2
440041,59.166.0.3,21511,149.171.126.9,21,114,2,6.335154,1802,2088,31,...,NaN,2.0,2,2,2,4,2,2,2,2
440042,59.166.0.9,35433,149.171.126.0,80,114,2,2.200934,3498,166054,31,...,2.0,NaN,,1,1,2,4,2,2,2
440043,175.45.176.0,17293,149.171.126.17,110,114,2,0.942984,574,676,62,...,NaN,NaN,,1,1,2,4,2,2,2

### 空值处理

In [25]:
# A = A[~A.isin([np.nan, np.inf, -np.inf]).any(1)] #删除缺失值和无穷大
# 因为有近一半的空值，因此不能简单删除，所以将

In [26]:
print(A.isnull().any()) # 37,38列有空值

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38     True
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
dtype: bool

In [27]:
print(A.isnull().sum()) # 空值数量占到数据总量的一半

0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0
10          0
11          0
12          0
13          0
14          0
15          0
16          0
17          0
18          0
19          0
20          0
21          0
22          0
23          0
24          0
25          0
26          0
27          0
28          0
29          0
30          0
31          0
32          0
33          0
34          0
35          0
36          0
37    1348145
38    1429879
39          0
40          0
41          0
42          0
43          0
44          0
45          0
46          0
dtype: int64

In [28]:
pd.value_counts(A[37])

37
0.0     986791
1.0     188008
6.0       7902
4.0       6564
3.0        738
2.0        588
5.0        430
9.0        270
14.0       224
12.0       132
30.0        60
8.0         56
16.0        48
36.0        36
10.0        30
25.0        25
Name: count, dtype: int64

In [29]:
from scipy import stats # 使用众数填充
A[37] = A[37].replace(np.NaN,stats.mode(A[37])[0][0])

C:\Users\87211\AppData\Local\Temp\ipykernel_23136\1441392088.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  A[37] = A[37].replace(np.NaN,stats.mode(A[37])[0][0])
C:\Users\87211\AppData\Local\Temp\ipykernel_23136\1441392088.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[37] = A[37].replace(np.NaN,stats.mode(A[37])[0][0])

In [30]:
pd.value_counts(A[38])

38
0.0    1066593
1.0      43389
4.0        156
2.0         30
Name: count, dtype: int64

In [31]:
A[38] = A[38].replace(np.NaN,stats.mode(A[38])[0][0])

C:\Users\87211\AppData\Local\Temp\ipykernel_23136\127233682.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  A[38] = A[38].replace(np.NaN,stats.mode(A[38])[0][0])
C:\Users\87211\AppData\Local\Temp\ipykernel_23136\127233682.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[38] = A[38].replace(np.NaN,stats.mode(A[38])[0][0])

In [32]:
A

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,59.166.0.0,1390,149.171.126.6,53,120,2,0.001055,132,164,31,...,0.0,0.0,0,3,7,1,3,1,1,1
1,59.166.0.0,33661,149.171.126.9,1024,120,2,0.036133,528,304,31,...,0.0,0.0,0,2,4,2,3,1,1,2
2,59.166.0.6,1464,149.171.126.7,53,120,2,0.001119,146,178,31,...,0.0,0.0,0,12,8,1,2,2,1,1
3,59.166.0.5,3593,149.171.126.5,53,120,2,0.001209,132,164,31,...,0.0,0.0,0,6,9,1,1,1,1,1
4,59.166.0.3,49664,149.171.126.0,53,120,2,0.001169,146,178,31,...,0.0,0.0,0,7,9,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440039,59.166.0.5,33094,149.171.126.7,43433,114,5,0.087306,320,1828,31,...,NaN,NaN,,1,2,3,3,1,1,3
440040,59.166.0.7,20848,149.171.126.4,21,114,2,0.365058,456,346,31,...,NaN,2.0,2,2,2,2,2,2,2,2
440041,59.166.0.3,21511,149.171.126.9,21,114,2,6.335154,1802,2088,31,...,NaN,2.0,2,2,2,4,2,2,2,2
440042,59.166.0.9,35433,149.171.126.0,80,114,2,2.200934,3498,166054,31,...,2.0,NaN,,1,1,2,4,2,2,2
440043,175.45.176.0,17293,149.171.126.17,110,114,2,0.942984,574,676,62,...,NaN,NaN,,1,1,2,4,2,2,2

### 字符型处理

In [33]:
A.shape

(2540047, 47)

In [34]:
for i,j in zip(A.columns,A.dtypes):
    print(i,j)

0 object
1 object
2 object
3 object
4 int64
5 int64
6 float64
7 int64
8 int64
9 int64
10 int64
11 int64
12 int64
13 int64
14 float64
15 float64
16 int64
17 int64
18 int64
19 int64
20 int64
21 int64
22 int64
23 int64
24 int64
25 int64
26 float64
27 float64
28 int64
29 int64
30 float64
31 float64
32 float64
33 float64
34 float64
35 int64
36 int64
37 float64
38 float64
39 object
40 int64
41 int64
42 int64
43 int64
44 int64
45 int64
46 int64

In [35]:
A[1] = A[1].apply(lambda x:str(x).replace('0x000b','').replace('0','')) # 将垂直制表符替换成0
A[39] = A[39].apply(lambda x:str(x).replace('0x000b','').replace('0','')) # 将垂直制表符替换成0

C:\Users\87211\AppData\Local\Temp\ipykernel_23136\825562288.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[1] = A[1].apply(lambda x:str(x).replace('0x000b','').replace('0','')) # 将垂直制表符替换成0
C:\Users\87211\AppData\Local\Temp\ipykernel_23136\825562288.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[39] = A[39].apply(lambda x:str(x).replace('0x000b','').replace('0','')) # 将垂直制表符替换成0

In [36]:
A[1] = LabelEncoder().fit_transform(A[1]) # 对第一列编码
A[39] = LabelEncoder().fit_transform(A[39]) # 对第39列编码

C:\Users\87211\AppData\Local\Temp\ipykernel_23136\1636758985.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[1] = LabelEncoder().fit_transform(A[1]) # 对第一列编码
C:\Users\87211\AppData\Local\Temp\ipykernel_23136\1636758985.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[39] = LabelEncoder().fit_transform(A[39]) # 对第39列编码

In [40]:
#将object列转换为float
A[1] = A[1].astype(float)
print(A[2])
A[2] = A[2].astype(float)

0          149.171.126.6
1          149.171.126.9
2          149.171.126.7
3          149.171.126.5
4          149.171.126.0
               ...
440039     149.171.126.7
440040     149.171.126.4
440041     149.171.126.9
440042     149.171.126.0
440043    149.171.126.17
Name: 2, Length: 2540047, dtype: object

C:\Users\87211\AppData\Local\Temp\ipykernel_23136\2651610077.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A[1] = A[1].astype(float)

ValueError: could not convert string to float: '149.171.126.6'

# 标准化

In [41]:
from sklearn.preprocessing import StandardScaler

for x in range(A.shape[1]):
    d=A.iloc[:,x]
    try:
        A.iloc[:,x]=d.astype(float)
    except:
        A.iloc[:,x]=LabelEncoder().fit_transform(d)
    #print(x)  #输出特征序号
Dt1=StandardScaler().fit_transform(A)

In [42]:
Dt1.shape

(2540047, 47)

In [43]:
Dt1

array([[-0.15295161, -1.33730157,  0.53166869, ..., -0.42962032,
        -0.41991297, -0.51925215],
       [-0.15295161, -0.22413951,  0.9722954 , ..., -0.42962032,
        -0.41991297, -0.43042863],
       [ 0.64217876, -1.29305374,  0.67854426, ..., -0.31166208,
        -0.41991297, -0.51925215],
       ...,
       [ 0.24461358, -0.92552117,  0.9722954 , ..., -0.31166208,
        -0.25795507, -0.43042863],
       [ 1.03974394, -0.11466824, -1.81834046, ..., -0.31166208,
        -0.25795507, -0.43042863],
       [-0.81556025, -1.12854062, -0.49646031, ..., -0.31166208,
        -0.25795507, -0.43042863]])

# 保存

In [52]:
np.save('../../data/nb15/data.npy',Dt1)

# 标签数值化

In [53]:
L2 = a[48]

In [54]:
L2

0         0
1         0
2         0
3         0
4         0
         ..
440039    0
440040    0
440041    0
440042    0
440043    1
Name: 48, Length: 2540047, dtype: int64

In [55]:
#查看数据类分布
from collections import Counter
sorted(Counter(L2).items())

[(0, 2218764), (1, 321283)]

In [56]:
L2.shape[0]

2540047

In [57]:
label2 = L2.values.reshape(L2.shape[0],1)  #将标签再重塑为列向量形式,最终分类需要这种格式

In [58]:
label2

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int64)

In [59]:
np.save('../../data/nb15/label2.npy',label2)

# 转为多分类标签

In [60]:
import copy

In [61]:
L10 = copy.copy(a[47])

In [62]:
L10

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
            ...
440039         NaN
440040         NaN
440041         NaN
440042         NaN
440043    Exploits
Name: 47, Length: 2540047, dtype: object

In [63]:
L10 = L10.replace(np.NaN,0)

In [64]:
l = L10.unique()

In [65]:
l

array([0, 'Exploits', 'Reconnaissance', 'DoS', 'Generic', 'Shellcode',
       ' Fuzzers', 'Worms', 'Backdoors', 'Analysis', ' Reconnaissance ',
       'Backdoor', ' Fuzzers ', ' Shellcode '], dtype=object)

In [66]:
Generic             215481
Exploits             44525
Fuzzers              19195
DoS                  16353
Reconnaissance       12228
Fuzzers               5051
Analysis              2677
Backdoor              1795
Reconnaissance        1759
Shellcode             1288
Backdoors              534
Shellcode              223
Worms                  174

SyntaxError: invalid syntax (2453592395.py, line 1)

In [67]:
pd.value_counts(L10)

47
0                   2218764
Generic              215481
Exploits              44525
 Fuzzers              19195
DoS                   16353
 Reconnaissance       12228
 Fuzzers               5051
Analysis               2677
Backdoor               1795
Reconnaissance         1759
 Shellcode             1288
Backdoors               534
Shellcode               223
Worms                   174
Name: count, dtype: int64

In [68]:
#将15分类标签数值化
i=0
for i in range(L10.shape[0]):
    if L10.iloc[i] == "Exploits":
        L10.iloc[i]=1
    elif (L10.iloc[i] == "Reconnaissance")|(L10.iloc[i] == " Reconnaissance "):
        L10.iloc[i]=2
    elif L10.iloc[i] == "DoS":
        L10.iloc[i]=3
    elif L10.iloc[i] == "Generic":
        L10.iloc[i]=4
    elif (L10.iloc[i] == "Shellcode")|(L10.iloc[i] == " Shellcode "):
        L10.iloc[i]=5
    elif (L10.iloc[i] == " Fuzzers")|(L10.iloc[i] == " Fuzzers "):
        L10.iloc[i]=6
    elif L10.iloc[i] == "Worms":
        L10.iloc[i]=7
    elif (L10.iloc[i] == "Backdoors")|(L10.iloc[i] == "Backdoor"):
        L10.iloc[i]=8
    elif L10.iloc[i] == "Analysis":
        L10.iloc[i]=9
        
        i=i+1

In [69]:
pd.value_counts(L10)

47
0    2218764
4     215481
1      44525
6      24246
3      16353
2      13987
9       2677
8       2329
5       1511
7        174
Name: count, dtype: int64

In [70]:
L10.shape

(2540047,)

In [71]:
label10 = L10.values.reshape(L10.shape[0],1)  #将标签再重塑为列向量形式,最终分类需要这种格式

In [72]:
label10.shape

(2540047, 1)

# 保存成npy

In [74]:
np.save('../../data/nb15/label10.npy',label10)